import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { NavBar } from "@/components/navbar/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CheckINN",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className=" ">
      <body className="h-full  bg-powerBackground">
        <NavBar />
        <div className="pt-16  h-full ">{children}</div>
        {/* FOOTER */}
      </body>
    </html>
  );
}
